const HoodiesSweatshirts = [

    {
        id: 51,
        name: 'Nike Sportswear Tech Fleece',
        title: 'Mens Full-Zip Hoodie',
        price: 130,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/54591fa0-e256-4ce6-87c5-61dd4fd20320/sportswear-tech-fleece-mens-full-zip-hoodie-5ZtTtk.png',
        description: 'Ready to rock the warmth and comfort of your favorite weekender hoodie, but need to keep your look clean? This Nike Tech Fleece hoodie strikes the right balance with a lightweight, low-profile design that packs in the heat without adding bulk. You can layer with ease whether youre lounging at home or making your city commute.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 52,
        name: 'Nike Sportswear Tech Fleece',
        title: 'Mens Crew Sweatshirt',
        price: 100,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b99d85ad-9322-4c0e-aec2-94d7b18749c1/sportswear-tech-fleece-mens-crew-sweatshirt-pfjm2W.png',
        description: 'This crew perfects the things you already love about sweatshirts. The smooth, low-loft Tech Fleece keeps you warm without feeling bulky, so you can layer with ease during the chilly months. Stretchy trim on the cuffs and hem help hold in your heat, and the signature zippered pocket on the sleeve keeps you equipped for your city adventures.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 53,
        name: 'Nike ACG "Wolf Lichen Caps"',
        title: 'Mens Mid-Layer Top',
        price: 180,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f4affa81-12f3-4a23-8b9d-56c246e4854e/acg-wolf-lichen-caps-mens-mid-layer-top-r7npGW.png',
        description: 'Just the ticket for cool weather, this lightweight fleece mid-layer delivers the versatility you need for your next adventure. Roomy enough to fit over a base layer but still comfortable under a jacket or vest, its stretchy knit Polartec® fabric feels airy and ultra soft. Plus, it comes with a zippered sack for easy packing.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 54,
        name: 'Nike ACG',
        title: 'Nike Therma-FIT Fleece Allover Print Crew',
        price: 125,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2f7eb7c8-a209-407f-b504-0d051cef465a/acg-nike-therma-fit-fleece-allover-print-crew-Bcf7pQ.png',
        description: 'With an allover print inspired by the High Sierras, this heavyweight fleece crew brings the warmth. Nike Therma-Fit tech helps to manage your body’s natural heat and the roomy fit makes it perfect for layering.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 55,
        name: 'Nike Dri-FIT Standard Issue',
        title: 'Mens Pullover Basketball Hoodie',
        price: 105,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/48051fbd-6f96-43f6-ac22-c54af7829910/dri-fit-standard-issue-mens-pullover-basketball-hoodie-gbxBxp.png',
        description: 'Our sweat-wicking Standard Issue Hoodie combines a classic look with the feel of modern performance for beyond the basketball court. Its made from soft, heavyweight fabric, with graphics giving it up for the stars from the rookie class of 96.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 56,
        name: 'Nike Trail Magic Hour',
        title: 'Mens Dri-FIT Running Hoodie',
        price: 90,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2fcef2d5-1f02-4f03-8ad1-9f00a34a1122/trail-magic-hour-mens-dri-fit-running-hoodie-f1s4ph.png',
        description: 'Start and finish your outdoor adventure with this comfortable trail running hoodie. Its made for those pre- or post-run moments where a little extra insulation is welcome. Its comfortable, lightweight feel keeps you feeling warm inside and out, like those waning moments of a beautiful sunset. Extra coverage courtesy of extendable sleeves helps keep the chill away from your hands.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 57,
        name: 'Nike Standard Issue',
        title: 'Mens Dri-FIT Pullover Basketball Hoodie',
        price: 90,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/db01f4a7-201d-4052-9d37-fac0492b2635/standard-issue-mens-dri-fit-pullover-basketball-hoodie-vgb6ww.png',
        description: 'This sweat-wicking combines a classic look with the feel of modern performance for beyond the basketball court. Its soft, yet heavyweight, with coverage thats ready to go right out of your gym bag.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    }, {
        id: 58,
        name: 'Nike Standard Issue',
        title: 'Mens Dri-FIT Crew Basketball Top',
        price: 75,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ab74cac2-f142-450d-ad47-3de9b7fec162/standard-issue-mens-dri-fit-crew-basketball-top-Kww2cz.png',
        description: 'Nike Basketball offers the Standard Issue Top, part of a collection that combines classic looks with a modern performance feel. It has soft, heavyweight fabric mixed with sweat-wicking technology thats ready to go right out of your gym bag. Wear it alone or as an extra layer to help take the chill off.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 59,
        name: 'Nike Sportswear Club Fleece',
        title: 'Pullover Hoodie',
        price: 60,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6e601618-6281-4975-9ac2-44e8330db933/sportswear-club-fleece-pullover-hoodie-Gw4Nwq.png',
        description: 'A closet staple, the Nike Sportswear Club Fleece Pullover Hoodie combines classic style with the soft comfort of fleece.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 60,
        name: 'Nike Sportswear Club Fleece',
        title: 'Crew',
        price: 55,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/098b6f6f-de01-4a85-97ad-05599af6fb68/sportswear-club-fleece-crew-TWcqLw.png',
        description: 'A closet staple, the Nike Sportswear Club Fleece Crew combines a classic embroidered logo on the left chest with the soft comfort of fleece for an elevated everyday look.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 61,
        name: 'Nike Tech Fleece Lightweight',
        title: 'Mens Full-Zip Hooded Jacket',
        price: 125,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/09f7ff85-0e4c-4f59-9240-28e994f9f6d8/tech-fleece-lightweight-mens-full-zip-hooded-jacket-PgWWQd.png',
        description: 'Perfect for warmer weather, this classic full-zip design gives you a dose of signature Tech Fleece DNA in a lightweight, stretchy knit fabric. Premium finishes, like the taped trim and silicone Futura logo give you a polished look you can dress up or down. ',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 62,
        name: 'Nike Tech Fleece',
        title: 'Mens Pullover Graphic Hoodie',
        price: 120,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6f31f70f-4e52-4c63-89ed-20fb14179a4c/tech-fleece-mens-pullover-graphic-hoodie-3GQNg6.png',
        description: 'Our Tech Fleece Hoodie elevates a layering essential with premium, low-profile warmth. Signature details like contrast taped trim and bonded pockets provide an elevated look. The roomy fit and articulation at the shoulders and sleeves creates a more natural shape for relaxed comfort and easy movement.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 63,
        name: 'Nike Dry',
        title: 'Mens Dri-FIT Hooded Fitness Full-Zip',
        price: 75,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1ad17247-0a10-4387-88a2-b9c71f7f6d76/dry-mens-dri-fit-hooded-fitness-full-zip-qP1nt7.png',
        description: 'The Nike Dry hoodie is made of soft French terry fabric with sweat-wicking power to help keep you warm and dry when youre warming up, cooling down or catching your breath between sets. This product is made with 100% sustainable materials, using a blend of both recycled polyester and organic cotton fibers. The blend is at least 10% recycled fibers or at least 10% organic cotton fibers.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 64,
        name: 'Nike Dri-FIT',
        title: 'Mens Full-Zip Training Hoodie',
        price: 75,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/03d3104f-16cb-44de-9f7c-1a815a809914/dri-fit-mens-full-zip-training-hoodie-cnXQ8n.png',
        description: 'The Nike Dri-FIT Hoodie outfits you in lasting warmth and comfort before, during and after workouts on cooler days. Soft fleece holds heat in, while sweat-wicking technology helps keep you dry.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 65,
        name: 'Nike Yoga',
        title: 'Mens Dri-FIT Pullover',
        price: 100,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/50784801-a516-499c-bf70-cf8bc07ea4bd/yoga-mens-dri-fit-pullover-lm5WSd.png',
        description: 'For the searchers, the dreamers and the doers, our sweat-wicking, textured hoodie is here for all your poses on the mat. We designed it with minimal seams and soft, stretchy fabric so you can find your flow with ease. Plus, the hood adds cozy coverage when youre looking for extra focus.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 66,
        name: 'Nike Yoga Texture',
        title: 'Mens Nike Dri-FIT Long-Sleeve Yoga Top',
        price: 80,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f1fc5335-1d82-422e-a0b3-697a070bb44f/yoga-texture-mens-nike-dri-fit-long-sleeve-yoga-top-d3sjn6.png',
        description: 'For the searchers, the dreamers and the doers, our sweat-wicking, textured top is here for all your poses on the mat. We added minimal seams and soft, stretchy fabric so you can find your flow with ease.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 67,
        name: 'Nike Solo Swoosh',
        title: 'Nike Solo Swoosh',
        price: 100,
        img: 'https://www.nike.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/p.js',
        description: 'Celebrate the power and simplicity of the Swoosh. This warm, brushed fleece hoodie is made with some extra room through the shoulders, chest and body for easy comfort and laid-back, nostalgic style. Thick, stretchy ribbing at the cuffs and hem help hold the hoodie in place when you move and seal in your warmth when conditions cool. Our Solo Swoosh is embroidered on the left chest to keep your look clean and effortless.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 68,
        name: 'Nike Solo Swoosh',
        title: 'Mens Fleece Crew',
        price: 90,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/40bb484d-c6d2-4a5c-b86c-f8bc862a635a/solo-swoosh-mens-fleece-crew-dxFM6v.png',
        description: 'Celebrate the power and simplicity of the Swoosh. This warm fleece crew is made with some extra room through the shoulders, chest and body for easy comfort and laid-back, nostalgic style. Stretchy ribbed openings help hold the crew in place when you move and seal in your body heat when the weather cools.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 69,
        name: 'Nike Sportswear Club Fleece',
        title: 'Mens Pullover Hoodie',
        price: 75,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/22f8e0fe-33fa-467b-a124-892dd0b1c624/sportswear-club-fleece-mens-pullover-hoodie-JzxvJQ.png',
        description: 'Surround yourself with good vibes in the Nike Sportswear Club Fleece Hoodie. Our midweight brushed fleece feels extra soft on the inside and smooth on the outside, helping you stay cozy while keeping its structured shape. Graphics inspired by 80s and 90s aesthetics add wild style.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 70,
        name: 'Nike Sportswear Club Fleece',
        title: 'Mens Trippy Safari Sweatshirt',
        price: 75,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e24be5d8-6ee4-4e7b-8eb2-869225226b07/sportswear-club-fleece-mens-trippy-safari-sweatshirt-pTXMGw.png',
        description: 'A closet staple, this sweatshirt brings safari vibes in a comfy, fleece layer. So hop in the 4x4 and earn your stripes—youre ready for where the adventure takes you.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 71,
        name: 'Nike Therma',
        title: 'Mens Therma-FIT Full-Zip Fitness Top',
        price: 70,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/045f5c5e-b48f-46b0-b0f2-1c7b1f6a9d17/therma-mens-therma-fit-full-zip-fitness-top-vsR4Rm.png',
        description: 'Bring the heat to your cold weather workout with the Therma Top. Supersoft fleece keeps the comfort levels high while you take your exercise routine to the next level. A relaxed feel means you can stretch and bench without anything holding you back.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 72,
        name: 'Nike Dry Graphic',
        title: 'Mens Dri-FIT Hooded Fitness Pullover',
        price: 70,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b711c6b9-a0af-4a85-864d-f4c36c988815/dry-graphic-mens-dri-fit-hooded-fitness-pullover-PcdFd2.png',
        description: 'The Nike Dry Graphic hoodie is made with sweat-wicking technology helps you stay dry before, during or after your workout. This product is made with 100% sustainable materials, using a blend of both recycled polyester and organic cotton fibers. The blend is at least 10% recycled fibers or at least 10% organic cotton fibers.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 73,
        name: 'Nike Yoga Dri-FIT',
        title: 'Mens Full-Zip Jacket',
        price: 85,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/28b580f3-70f1-4df3-bd97-1af5e069c015/yoga-dri-fit-mens-full-zip-jacket-d8QsnX.png',
        description: 'The Nike Yoga Dri-FIT Jacket is a soft, light layer that keeps you comfortably covered before, during and after your practice. This product is made with at least 75% recycled polyester fibers.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 74,
        name: 'Nike Yoga Dri-FIT',
        title: 'Mens Lightweight Hoodie',
        price: 80,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/048317c5-7dcc-4ffd-8793-8f3c0776ff71/yoga-dri-fit-mens-lightweight-hoodie-4CclJD.png',
        description: 'Peace is a state of mind, and this hoodie is crafted to wear wherever you try to find your calm. We made it cozy and light, so you can get the most out of your movement on the mat.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 75,
        name: 'Jordan Flight Fleece',
        title: 'Mens Pullover Hoodie',
        price: 97,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d060cf3c-4d86-4811-a1dd-303d98e4263f/jordan-flight-fleece-mens-pullover-hoodie-sNHVMK.png',
        description: 'Meet your new go-to hoodie. Heavyweight fleece feels super soft, and the comfy, relaxed fit will have you reaching for it again and again. An oversized Jumpman label is sewn on front-and-center, making this wardrobe staple anything but basic.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 76,
        name: 'Jordan Wordmark',
        title: 'Mens Fleece Hoodie',
        price: 120,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/458eb318-6e09-4401-b707-1fff16fc9fc7/jordan-wordmark-mens-fleece-hoodie-LmSppR.png',
        description: 'Sometimes less is more. Bundle up in this premium Jordan hoodie made from plush, heavyweight fleece. It serves straightforward quality—and the serious style your wardrobe requires.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 77,
        name: 'Nike ACG Therma-FIT',
        title: 'Fleece Pullover Hoodie',
        price: 125,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/265e1596-dd79-437f-8017-30d42c270e60/acg-therma-fit-fleece-pullover-hoodie-njCV8f.png',
        description: 'Spacious and ultra-warm, this ACG "Tuff Fleece" hoodie is designed to turn up the heat in cold conditions. It gives you plenty of room to layer underneath, while the snug ribbed cuffs and hem help seal in your warmth. Our Therma-FIT tech works to regulate your body temp, helping you stay toasty at base camp or in your backyard by the fire pit, counting stars with your friends.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 78,
        name: 'Nike ACG Therma-FIT',
        title: 'Fleece Crew',
        price: 105,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0f42c441-0edb-497e-95f0-5ca3e131c9ff/acg-therma-fit-fleece-crew-Ckxhvf.png',
        description: 'Spacious and ultra-warm, this ACG "Tuff Fleece" crew is designed to turn up the heat in cold conditions. It gives you plenty of room to layer underneath, while the snug ribbed openings help seal in warmth. Our Therma-FIT Tech you stay toasty at base camp or in your backyard by the fire pit, counting stars with your friends.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 79,
        name: 'Nike Solo Swoosh',
        title: 'Mens French Terry Pullover Hoodie',
        price: 100,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/217dba41-a062-489e-83ba-d1aa75abc695/solo-swoosh-mens-french-terry-pullover-hoodie-drNNQB.png',
        description: 'This warm, fleece hoodie is made with some extra room through the shoulders, chest and body for easy comfort and laid-back, nostalgic style. Thick, stretchy ribbing at the cuffs and hem help hold the hoodie in place and give a premium feel. Our Solo Swoosh is embroidered on the left chest to keep your look clean and effortless.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 80,
        name: 'Nike Sportswear Club Fleece',
        title: 'Mens Full-Zip Hoodie',
        price: 65,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3a39147f-bee2-4928-8adb-f45ab2d6faae/sportswear-club-fleece-mens-full-zip-hoodie-nR8tst.png',
        description: 'The Nike Sportswear Club Fleece Hoodie combines soft fabric with simple street style thats versatile enough for everyday use. With a full zipper that goes to the chin, its the perfect extra layer on a chilly day.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 81,
        name: 'Nike Sportswear Club Fleece',
        title: 'Mens Graphic Pullover Hoodie',
        price: 65,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d4ousovkmaqcl9eypocd/sportswear-club-fleece-mens-graphic-pullover-hoodie-R9w74B.png',
        description: 'A closet staple, the Nike Sportswear Club Fleece Pullover Hoodie gives you soft comfort in a street-ready style for an elevated, everyday look that you really can wear every day.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 82,
        name: 'Nike Sportswear Club Fleece',
        title: 'Mens Graphic Crew',
        price: 60,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/641aad63-6eca-40b6-977e-42f5ca119cf8/sportswear-club-fleece-mens-graphic-crew-56GFJR.png',
        description: 'A closet staple, the Nike Sportswear Club Fleece Crew combines a bold Futura logo on the chest with the soft comfort of fleece for an elevated, everyday look.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 83,
        name: 'Nike Solo Swoosh',
        title: 'Mens 1/4-Zip Top',
        price: 105,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a81c5252-9fd5-46ad-973e-4f39b1f11d01/solo-swoosh-mens-1-4-zip-top-9MDrWh.png',
        description: 'This track-inspired Solo Swoosh jacket is built on clean lines with soft blended fabric in a roomy fit you can layer up or down. The 1/4-zip design lets you change up your style and coverage while soft ribbing in the hem and cuffs help lock in your body heat.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 84,
        name: 'Nike Solo Swoosh',
        title: 'Mens Full-Zip Hoodie',
        price: 110,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d13f96ba-894f-46c0-97d3-dffc42e759e4/solo-swoosh-mens-full-zip-hoodie-8bKgZZ.png',
        description: 'A true classic, our Solo Swoosh full-zip hoodie is made with supersoft fleece for smooth, easy comfort. The simplicity of the design lets you pair it up or down for clean, casual daily wear.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 85,
        name: 'England Club Fleece',
        title: 'Mens Sweatshirt',
        price: 65,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/21b7218d-20af-43e6-b6df-e85bcc9d739f/england-club-fleece-mens-sweatshirt-7Dlx2j.png',
        description: 'We took an everyday classic and infused it with three lions pride to create a comfortable staple you’ll want to wear again and again. Crafted from midweight brushed fleece that feels extra soft on the inside and smooth on the outside, this classic-fit sweatshirt helps keep you warm while you cheer on your team.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 86,
        name: 'Jordan Flight MVP',
        title: 'Mens Fleece Pullover Hoodie',
        price: 92,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/169bfcba-7a38-497c-a619-f569b7038315/jordan-flight-mvp-mens-fleece-pullover-hoodie-V2wtq7.png',
        description: 'Start the day right, with a hoodie that serves retro vibes for breakfast. Soft fleece feeds your need for cozy, and a big crackle-printed Wheaties graphic ups the vintage aesthetic. Plus, youve got MJs signature on your heart—a reminder that you can take on anything.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 87,
        name: 'Nike SB',
        title: 'Fleece Pullover Skate Hoodie',
        price: 76,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5cf2acba-671e-453d-a3e5-15b64931f7d7/sb-fleece-pullover-skate-hoodie-sSDNnR.png',
        description: 'Bringing a new meaning to the "SB" in "Nike SB," this hoodie celebrates one of the best times of year to hop on your board. Cut with some room through the chest, shoulders and body, this casual-fitting hoodie makes for easy movement and layering. Throw it on during your week off and skate hard.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 88,
        name: 'Nike Sportswear Tech Fleece',
        title: 'Mens 1/2-Zip Top',
        price: 102,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7ce23e59-aab7-4975-9092-cef48914b6c9/sportswear-tech-fleece-mens-1-2-zip-top-GgF0LM.png',
        description: 'Looking for the perfect mid layer? This fresh take on Tech Fleece gives you a half-zip, pullover option. Its designed to frame your body for an athletic fit you can layer. Low-profile fleece adds comfy warmth without the weight and signature taped trim keeps your look polished.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 89,
        name: 'Tiger Woods',
        title: 'Mens Knit Golf Sweater',
        price: 94,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/50b13cd1-5c01-4432-81b9-5849052998e9/tiger-woods-mens-knit-golf-sweater-XlMQrh.png',
        description: 'Cozy up in the Tiger Woods Sweater. Crafted from a premium merino wool blend, its designed to keep you warm and comfortable when the chill sets in. Thoughtful details, like the stretchy mesh stripe down the spine, let you move freely on and off the course.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 90,
        name: 'Nike Therma-FIT Standard Issue',
        title: 'Mens Winterized Full-Zip Basketball Hoodie',
        price: 62,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/991dd4ee-a5c0-49c3-8479-0ec16dcfd600/therma-fit-standard-issue-mens-winterized-full-zip-basketball-hoodie-910BCJ.png',
        description: 'Take on the rain and cold in our winterized Standard Issue Hoodie. We designed it with a spacious feel and soft fleece for warmth that moves with you. Our classic Swoosh is outlined with a chain graphic, paying respect to those who earn their spot on the floor.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 91,
        name: 'Jordan',
        title: 'Mens Pullover Hoodie',
        price: 80,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/76f0b96c-5dea-4164-aace-3425306ff177/jordan-mens-pullover-hoodie-cK4HGz.png',
        description: 'Rep some classic AJ1s up top—without actually having to drape em over your shoulders. Made of the soft fleece you love, this hoodie will keep you feeling cozy through the cold season.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 92,
        name: 'Nike Dri-FIT',
        title: 'Mens Long-Sleeve Fitness Top',
        price: 80,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/03895bd5-5f6e-4c6c-87a1-5325378da02c/dri-fit-mens-long-sleeve-fitness-top-rWqN2D.png',
        description: 'No need to pack your boxes when you work with the Nike Moving Co. Just throw on this sweat-wicking top and get moving with lightweight French terry fabric that feels soft while letting you get the most out of your stride. Stretch, run or throw down some reps—were ready to move with you.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 93,
        name: 'Nike Sportswear Club Fleece',
        title: 'Pullover Hoodie',
        price: 70,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/77ad621f-1900-40d5-b057-13b8de0702e4/sportswear-club-fleece-pullover-hoodie-rx92Dg.png',
        description: 'Be kind and comfy in this Club Fleece hoodie. A closet staple, its lightweight brushed fleece feels extra soft on the inside and smooth on the outside, helping you stay cozy while keeping its structured shape. Thick printed graphics feature a sweet message.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 94,
        name: 'Nike ESC',
        title: 'Mens Knit Pullover Hoodie ',
        price: 320,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5a1d8568-7bf3-480a-8cce-cb416a7ed48d/esc-mens-knit-pullover-hoodie-0Sk6qw.png',
        description: 'We obsessed over every detail and made this sweatshirt from an ultra-soft knit cotton jersey for warmth and breathable comfort. Its designed to fit with some room through the shoulders, chest and body for easy movement and layering.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 95,
        name: 'Nike Club Fleece',
        title: 'Mens Pullover Hoodie',
        price: 55,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6275020a-d4d2-4256-a9b0-726c34ca8603/club-fleece-mens-pullover-hoodie-PRBh5r.png',
        description: 'Layer up for chilly weather while repping your favorite sport in this Nike hoodie. It has a "LACROSSE" graphic front and center on our incredibly soft Club Fleece that helps keep you warm and comfortable.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 96,
        name: 'Nike Swoosh',
        title: 'Mens Hoodie',
        price: 55,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/80f703c3-28e9-429a-a376-781b8fbd579b/swoosh-mens-hoodie-9NnLkK.png',
        description: 'Celebrate 25 years of a soccer icon with this classic-fit Nike hoodie. The Mercurial has been the catalyst for some of the most memorable moments the game has ever produced. Its got us wondering: What moments will you etch into our memories over the next 25 years?',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 97,
        name: 'Jordan Flight Heritage',
        title: 'Mens Cardigan',
        price: 150,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2b346b9d-c3d1-4d76-b092-4a406d113d8c/jordan-flight-heritage-mens-cardigan-pLc4v6.png',
        description: 'Layer up in this statement-making staple. A soft, straightforward cardigan gets a glow-up with all-over elephant print (a nod to the AJ3) thats knit right into the soft fabric.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 98,
        name: 'Jordan Dri-FIT Sport',
        title: 'Mens Fleece Sleeveless Hoodie',
        price: 62,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7d2ef1d6-1db0-4bb1-bfdd-f44c2bd7dc5c/jordan-dri-fit-sport-mens-fleece-sleeveless-hoodie-TSCPg7.png',
        description: 'Ball out of control in this sleeveless hoodie. Lightweight fleece enhanced with sweat-wicking tech combines with ribbed side panels to keep you fresh. Concealed side pockets keep your look streamlined and your stuff secure.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 99,
        name: 'NikeCourt',
        title: 'Mens Fleece Tennis Hoodie',
        price: 80,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6c7f3b69-5ef8-4156-875e-eceef46cc1d9/nikecourt-mens-fleece-tennis-hoodie-090q22.png',
        description: 'From the court to the streets and everywhere in between, the NikeCourt Hoodie will become your new favorite layer. Its smooth French terry fabric feels soft and warm. Stretchy ribbed fabric on the sides and under the sleeves gives you plenty of room to move. This product is made with at least 75% sustainable materials, using a blend of recycled polyester and organic cotton fibers. The blend is at least 10% recycled fibers or at least 10% organic cotton fibers.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },
    {
        id: 100,
        name: 'Jordan Flight Heritage',
        title: 'Mens Hoodie',
        price: 78,
        img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c239649a-472a-4238-bdd6-945d250ca12f/jordan-flight-heritage-mens-hoodie-Bxgwrs.png',
        description: 'Let your style game take off with this relaxed hoodie. You could be warming up on the court or posting up with friends for a little lunch—either way, your outfit will pop to life with its contrasting panels of subtle stone print.',
        size: ' XS, S, M, L, XL, 2XL, 3XL',
    },


]

export default HoodiesSweatshirts